# Conexión correcta a Supabase con el puerto 6543
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.hxbmlkqpkyebuhmokhlw
spring.datasource.password=@Sistemaadop
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración del pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# Configuración JPA (necesaria para que Hibernate funcione)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# ===============================
# CONEXIÓN A SUPABASE (POSTGRESQL) esto es para levantar en la nube
# ===============================
#spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres
#spring.datasource.username=postgres.hxbmlkqpkyebuhmokhlw
#spring.datasource.password=@Sistemaadop
#spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# CONFIGURACIÓN DE HIBERNATE (ORM) esto es para levantar en la nube
# ===============================
# "update" hace que Spring Boot cree o actualice las tablas automáticamente en Supabase
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
